cmake distributed proofs attempt
This doesn't work because it attempts to build all dependencies of
https:

    [ 16%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/event_groups.c.obj
    [ 16%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/list.c.obj
    [ 33%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/queue.c.obj
    [ 33%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/stream_buffer.c.obj
    [ 50%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/tasks.c.obj
    [ 50%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/timers.c.obj
    [ 50%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/portable/MSVC-MingW/port.c.obj
    /Users/karkhaz/code/rtos/freertos_kernel/portable/MSVC-MingW/port.c:36:11: fatal error:
      'mmsystem.h' file not found
        #include "mmsystem.h"
                 ^~~~~~~~~~~~

Touching that file also doesn't work:

    [ 50%] Building C object CMakeFiles/afr_kernel.dir/freertos_kernel/portable/MSVC-MingW/port.c.obj
    /Users/karkhaz/code/rtos/freertos_kernel/portable/MSVC-MingW/port.c:56:1: error: syntax error before 'WINAPI'
     static DWORD WINAPI prvSimulatedPeripheralTimer( LPVOID lpParameter );
    PARSING ERROR
    make[3]: *** [CMakeFiles/afr_kernel.dir/freertos_kernel/portable/MSVC-MingW/port.c.obj] Error 1
    make[2]: *** [CMakeFiles/afr_kernel.dir/all] Error 2
    make[1]: *** [CMakeFiles/afr_cbmc-https.dir/rule] Error 2
    make: *** [afr_cbmc-https] Error 2